### ISSUE TITLE
Cannot install new games after installing Arduventure

### ISSUE THREAD

**Issue by GridShopPlus** [TEAMarg/ID-46-Arduventure#3]
I bought a brand new arduboy and installed about 5 games, i tried arduventure and loved it. but now i cant install any new games to try. RESET wouldnt work and FLASHLIGHT mode wont work.

im only using game loaders to flash games to the system. whats the fix?

**Comment by soxfox** [comment]
On the [download](http://www.team-arg.com/ardu-downloads.html) page there is a notice with a [link](http://arduboy.com/arduventure/) to the instructions for reprogramming. To save space the developers disabled the standard USB connection code, and so you need to go to the main menu, select "UPLOAD", and hold the down key while uploading from the computer.

**Comment by JO3RI** [comment]
After installing Arduventure, you have to use de Arduino IDE and the needed libraries. Compile and upload an Arduboy example sketch once. When done and you have the example sketch on the Arduboy, you can continue using a game loader.

**Comment by GridShopPlus** [comment]
Ok i got it working, you guys are amazing coders and game makers! one thing the video should say is that you should install all the requirements for the arduino ide program for arduboy. then the second thing is to note that the port wont show up until you press the up or down key to upload. took two tries then and it worked.

**Comment by magilith** [comment]
whenever i follow the steps it gives me an error message. someone please help me
