### ISSUE TITLE
Please add a warning in the README.md about the special upload procedure

### ISSUE THREAD

**Issue by Pharap** [TEAMarg/ID-46-Arduventure#4]
It would be good to add a warning notice about the special upload procudure in the `README.md`.

Here's one I recently edited into the forum thread:

## Important!

**After uploading Arduventure to your Arduboy you won't be able to upload another game using the normal process.**

**If you want to put a new game on your Arduboy with Arduventure, you must follow these steps:**

1. Plug in your Arduboy to the PC you will use for reprogramming
2. Turn on the Arduboy and from the main menu of Arduventure select “UPLOAD”
3. When the on screen instructions appear, press and continue to hold the _down_ button. (This will place the Arduboy in bootloader mode, ready to be reprogrammed)
4. While continuing to hold the _down_ button, press the upload button from your PC
5. When the upload completes, let go of the _down_ button and after a short delay the new game will start

---

You can choose to reword the warning if you wish, but please add something like this when possible.

---

There's also a video demonstrating the procedure:

https://www.youtube.com/watch?v=TEmWprJv6Ik

**Comment by pahakalle** [comment]
You could just create a pull request

**Comment by Gaveno** [comment]
Added to Readme, thank you @Pharap

**Comment by Pharap** [comment]
@pahakalle
I didn't create a pull request because I was too busy at the time to follow up on any edits that might have been suggested - I'd rather leave it up to the authors to choose what warning they want to use and how it should be worded.

Similarly I didn't reply to your comment at the time because I didn't have the time spare to do so and eventually forgot about replying to the comment.

---

@Gaveno
Thank you.

Hopefully this will prevent a few "I can't upload anything" incidents, or at least make handling them easier.

By the way, the "You can choose to reword the warning if you wish, but please add something like this when possible." part was supposed to be a direction to you, not part of the warning, but it doesn't really matter now.
