### ISSUE TITLE
Not Compiling with Arduino IDE v1.8.6

### ISSUE THREAD

**Issue by uXeBoy** [TEAMarg/ID-46-Arduventure#5]
Not Compiling with Arduino IDE v1.8.6

see: https://community.arduboy.com/t/arduventure-failed-to-upload/6397

**Comment by per1234** [comment]
narrowing conversion will be treated as a warning again in the next Arduino IDE/Arduino AVR Boards release: https://github.com/arduino/ArduinoCore-avr/pull/38
However, it's still necessary to fix this issue to provide compatibility with Arduino IDE 1.8.6/Arduino AVR Boards 1.6.22.

Besides, all those warnings should be fixed anyway. This is a perfect example of why you should always have warnings turned up to the highest level and always fix all the warnings. They are there for a reason.

**Comment by Gaveno** [comment]
Cleaned up warnings in song arrays and a few others. Thanks!
